# Generated by Django 4.2.4 on 2024-08-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image_post_slug_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='Click on the title to check out the blog.'),
        ),
    ]
